name: Despliegue CI/CD a VPS con Apache

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js v22
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Instalar dependencias (npm ci)
      run: npm ci

    - name: Compilar Angular
      run: |
        npx ng analytics off
        npm run build -- --configuration production

    - name: Despliegue autom√°tico a Apache (VPS)
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        source: "dist/posts-get/browser/*"
        target: "/var/www/html/examen"
        strip_components: 3
